version: '3.8'

services:

  frontend:
    container_name: jobstreet-dev
    image: jobstreet-dev
    build: 
      context: .
      target: development
    volumes:
      - './src:/app/src'
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true