version: "3.8"

services:
  app:
    container_name: jobstreet-prod
    image: jobstreet-prod
    build:
      context: .
      target: production
    volumes:
      - './src:/app/src'
    ports:
      - 3000:3000