name: Frontend Jobstreet CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-jobstreet-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client
        
      - name: Setup remote server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH into remote server and setup environment
        env:
          ENV_JOBSTREET_FRONTEND: ${{ secrets.ENV_JOBSTREET_FRONTEND }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.FRONTEND_REMOTE_SERVER_USERNAME }}@${{ secrets.FRONTEND_REMOTE_SERVER_ADDRESS }} << 'ENDSSH'
          # Update package
          sudo apt-get update && sudo apt-get install make
          
          # Create directory if not exists
          mkdir -p ~/jobstreet-sourcecode
          
          # Navigate to the directory
          cd jobstreet-sourcecode

          # Clone the source code repository
          if [ ! -d "frontend-jobstreet" ]; then
            git clone https://github.com/SEC-Jobstreet/frontend-jobstreet.git
          else
            cd frontend-jobstreet
            git checkout main
            git pull -f
            cd ..
          fi

          # Navigate to the cloned repository directory
          cd frontend-jobstreet

          # Create the .env file and add content from GitHub secrets
          echo "$ENV_JOBSTREET_FRONTEND" > .env

          # Build the Docker image
          make build_prod

          # Run docker
          make run_prod
          
          ENDSSH
